src/App.js, src/components/StickyForm.js
Created Form, imported the Form to the app and import Route in App.
=> feature-StickyForm - created form, imported to App

src/App.js, src/components/StickyForm.js
Accidentally merged form component into master and not dev. Merging Dev to be up to date with Master.
=> Merging Dev to be up to date with master

src/App.js
Added necessary functionality to App for Form Component
=> Feature App

public/manifest.json, src/App.js, src/components/StickyForm.js
Accidentally pulled into Master again in my excitement of getting the form working. Merging Master into Dev to catch up, will use Master to deploy into Netlify.
=> Merging Master into Dev

package.json, src/App.js, src/components/DisplaySticky/DisplaySticky.css, src/components/DisplaySticky/DisplaySticky.js, src/components/StickyForm/StickyForm.js, src/components/Whiteboard/Whiteboard.js, src/index.css
fixed function structure to match react architecture, created folders for components to organize CSS, created DisplaySticky component to display sticky tasks as well as set individual stickies too done.
=> Created DisplaySticky component, reorganized file structure (see comments)

package-lock.json, package.json, src/components/DisplaySticky/DisplaySticky.js, src/components/StickyForm/StickyForm.js, src/components/Whiteboard/Whiteboard.js
No longer need to refresh page to see new Stickies on the page, added Delete function to keep database data from growing too large.
=> Form Refresh Fix, added Delete Function for testing

package.json, src/App.js, src/components/DisplaySticky/DisplaySticky.js, src/components/StickyForm/StickyForm.js, src/components/Whiteboard/Whiteboard.js
Created the edit button to edit the specific sticky task. Tested the functionality and it worked.
In Whiteboard.js I added an "edit" route for the StickyForm and sent down the functions to be able to click the edit button, bring you to the edit page, and then allow you to make edits and then click update to save them.
=> Feature edit button

src/components/DisplaySticky/DisplaySticky.js, src/components/Whiteboard/Whiteboard.js
replaced the "delete sticky" text with a trashcan icon to delete individual sticky tasks
=> feature-delete-button

package-lock.json, package.json, src/App.js, src/components/DisplaySticky/DisplaySticky.js, src/components/Done/Done.js, src/components/StickyForm/StickyForm.js, src/components/Whiteboard/Whiteboard.js
Added transition effects for title, display sticky, and done sticky when you click refresh
added hover effects and click effects on done button, trash icon button, and not done button
=> Feature framer motion

src/components/DisplaySticky/DisplaySticky.js, src/components/StickyForm/StickyForm.js
re-added motion and hover effects for done and edit button
added hover effects for delete button and add person button
added motion effects for the sticky form
added drag effects for the display sticky
=> Feature framer motion done button

src/components/DisplaySticky/DisplaySticky.css, src/components/DisplaySticky/DisplaySticky.js, src/components/StickyForm/StickyForm.js
Adjusted the alignment of the sticky form when it appears on the screen.
=> Feature sticky form alignment fix

package-lock.json, package.json, src/App.js, src/components/DisplaySticky/DisplaySticky.js, src/components/Done/Done.js, src/components/Whiteboard/Whiteboard.css, src/components/Whiteboard/Whiteboard.js, src/index.js
Added mobile view Tab for Stickies list and Stickies/Done. Slightly cleaned code (unused vars) and fixed the DisplaySticky edit button CSS bug.
=> feature-Tab

src/components/DisplaySticky/DisplaySticky.js, src/components/Done/Done.js, src/components/StickyForm/StickyForm.js
Fixed alignment for sticky form on edit and create screen for mobile and laptop
Can drag the sticky form on the edit screen
Also fixed animations on buttons in the done tab
=> Feature sticky form alignment/edit screen

src/components/PersonForm/PersonForm.js, src/components/StickyForm/StickyForm.js
added same animation from sticky form to person form so it's more uniform 
when either "sticky task +" or" tasker +" button is clicked.
=> added animation to the tasker form

src/components/DisplayPeople/DisplayPeople.js, src/components/DisplaySticky/DisplaySticky.js, src/components/StickyForm/StickyForm.js, src/components/Whiteboard/Whiteboard.js
Can choose a tasker while creating a new Sticky.
=> Feature person

src/App.js, src/components/DisplaySticky/DisplaySticky.js, src/components/Done/Done.js
Removed the shadow color from the done, edit, trash icon, and plus sign button animations. 
Moved the motion tag to the child h1 in App.js
=> removed the color shadow of the button elements

src/components/PersonForm/PersonForm.js, src/components/StickyForm/StickyForm.js
Removed animation and motion from sticky form and person form
=> removed animation and motions from sticky and person forms

src/components/DisplaySticky/DisplaySticky.css, src/components/DisplaySticky/DisplaySticky.js
Removed the plus sign to add people on DisplaySticky
=> Feature remove plus sign

src/App.css, src/components/DisplayPeople/DisplayPeople.css, src/components/DisplaySticky/DisplaySticky.css, src/components/DisplaySticky/DisplaySticky.js, src/components/Done/Done.js, src/components/PersonForm/PersonForm.css, src/components/PersonForm/PersonForm.js, src/components/StickyForm/StickyForm.css, src/components/StickyForm/StickyForm.js, src/components/Whiteboard/Whiteboard.css, src/components/Whiteboard/Whiteboard.js
Added animation to the sticky form and person form to make it a little less snappy.
=> Fixing form animation

src/components/PersonForm/PersonForm.css, src/components/PersonForm/PersonForm.js
Fixed an issue where the person form when expanded wouldn't overlay over the stickies. It just pushed down the border.
It should overlay now similar to the sticky form drop down
=> fixed person form overlay

src/components/DisplaySticky/DisplaySticky.css, src/components/PersonForm/PersonForm.css, src/components/PersonForm/PersonForm.js
Fixed person form animation.
It wasn't overlaying like the sticky form.
I also removed the old add person icon from display sticky css, that wasn't needed anymore
=> Fixing person form animation

src/App.css, src/App.js, src/components/DisplaySticky/DisplaySticky.css, src/components/TeamPage/TeamPage.css, src/components/TeamPage/TeamPage.js, src/components/Whiteboard/Whiteboard.css, src/components/Whiteboard/Whiteboard.js
Created the team page for our app
=> Feature team/page

src/components/StickyForm/StickyForm.js, src/components/Whiteboard/Whiteboard.js
Fixed the button layout on the sticky form. Creating a sticky it should say "Add Sticky". When editing the sticky it should say "Update"
=> fixed button labels on stiky form create/edit
